services:
  app:
    build: .  # ローカル開発用にbuildを使用
    ports:
      - "443:443"  # HTTPS用
      - "8080:8080"  # 開発用
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/flashcard_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Qwqwqw12!!??
      OPENROUTER_API_KEY: "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"
    restart: on-failure

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: Qwqwqw12!!??
      MYSQL_DATABASE: flashcard_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mariadb", "-u", "root", "-pQwqwqw12!!??", "-e", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb_data:
    driver: local 